# Generated by Django 6.1.1 on 2026-10-05 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='foto de perfil')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono móvil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono fijo')),
                ('biography', models.TextField(blank=True, verbose_name='semblanza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='catalogs.academiclevel', verbose_name='nivel académico')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='catalogs.institution', verbose_name='institución')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='catalogs.state', verbose_name='estado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_areas', to='catalogs.area', verbose_name='área')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_areas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'área de usuario',
                'verbose_name_plural': 'áreas de usuario',
                'constraints': [models.UniqueConstraint(fields=('user', 'area'), name='unique_user_area')],
            },
        ),
    ]
